### PR TITLE
Add pull request template

### PR DESCRIPTION
**Pull request by mattmahn**
### Summary

I decided it'd be a good idea to have a template for PR descriptions, so that we can make it easier for those reviewing to know what to do&mdash;and such.
The :white_check_mark: / :red_circle: is so that a PR can be made and development continued, but potential reviewers do no waste their time reviewing.
### Checklist
- [x] Did you run `npm test`?
- [x] Did you update/add documentation for new methods or changed functionality?

Finally, is it ready to be reviewed and merged: YES :white_check_mark:
(Although, I think we're missing some items in Checklist.)
### How to Review
1. Read `.github/PULL_REQUEST_TEMPLATE.md`
2. State your opinion. Suggest any changes.
### Links
- [Release blog post about this GH feature](https://github.com/blog/2111-issue-and-pull-request-templates)

### CODE REVIEW

**Comment by trevinhofmann** [comment]
Should this be part of a CONTRIBUTING.md?

**Comment by trevinhofmann** [comment]
https://github.com/blog/1184-contributing-guidelines

**Comment by mattmahn** [comment]
It could, but by doing it this way the body of `.github/PULL_REQUEST_TEMPLATE.md` will be automatically copied into the text box when creating a new PR.

**Comment by trevinhofmann** [comment]
Oh, that's neat. I did not know that.

**Comment by trevinhofmann** [comment]
Oh, there's a link to it in the PR. My bad.

**Review by gearedmonkey — APPROVED** [review]

**Review by trevinhofmann — APPROVED** [review]

**Pull request merged**
